FROM flink:2.2

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install --break-system-packages apache-flink

RUN wget -P /opt/flink/lib \
https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/4.0.0-2.0/flink-sql-connector-kafka-4.0.0-2.0.jar

USER flink